### ISSUE TITLE
基于 calibre的导出文档报错!!!!

### ISSUE THREAD

**Issue by zhangxiangfeng** [lifei6671/mindoc#217]
完整的log内容
```
local_mindoc_1    | /tmp/a01246b650e04168bb30061527cd7e8b
local_mindoc_1    | /tmp/a01246b650e04168bb30061527cd7e8b/META-INF
local_mindoc_1    | epub目录 /tmp/a01246b650e04168bb30061527cd7e8b/content.epub
local_mindoc_1    | convert to epub
local_mindoc_1    | [ebook-convert /tmp/a01246b650e04168bb30061527cd7e8b/content.epub /tmp/a01246b650e04168bb30061527cd7e8b/output/book.epub]
local_mindoc_1    | 转换EPUB文档失败：exit status 1
local_mindoc_1    | convert to mobi
local_mindoc_1    | [ebook-convert /tmp/a01246b650e04168bb30061527cd7e8b/content.epub /tmp/a01246b650e04168bb30061527cd7e8b/output/book.mobi]
local_mindoc_1    | 转换MOBI文档失败：exit status 1
local_mindoc_1    | convert to pdf
local_mindoc_1    | [ebook-convert /tmp/a01246b650e04168bb30061527cd7e8b/content.epub /tmp/a01246b650e04168bb30061527cd7e8b/output/book.pdf --paper-size a4 --pdf-default-font-size 14 --pdf-header-template <p style='color:#8E8E8E;font-size:12px;'>_SECTION_</p> --pdf-footer-template <p style='color:#8E8E8E;font-size:12px;'>本文档使用 <a href='https://www.iminho.me' style='text-decoration:none;color:#1abc9c;font-weight:bold;'>MinDoc</a> 构建 <span style='ight'>- _PAGENUM_ -</span></p> --pdf-page-margin-left 72 --pdf-page-margin-top 72 --pdf-page-margin-right 72 --pdf-page-margin-bottom 72]
local_mindoc_1    | 转换PDF文档失败：exit status 1
local_mindoc_1    | convert to docx
local_mindoc_1    | [ebook-convert /tmp/a01246b650e04168bb30061527cd7e8b/content.epub /tmp/a01246b650e04168bb30061527cd7e8b/output/book.docx --docx-no-toc --docx-page-size a4 --docx-page-margin-left 72 --docx-page-margin-top 72 --docx-page-margin-right 72 --docx-page-margin-bottom 72]
local_mindoc_1    | 转换WORD文档失败：exit status 1
local_mindoc_1    | 2018/02/07 14:23:05.575 [E] [book_result.go:343] 转换文件错误：bug修复 => exit status 1
local_mindoc_1    | exit status 1
local_mindoc_1    | exit status 1
local_mindoc_1    | exit status 1 
local_mindoc_1    | 2018/02/07 14:23:05.575 [E] [document.go:894] 转换文档失败：bug修复 -> exit status 1
local_mindoc_1    | exit status 1
local_mindoc_1    | exit status 1
local_mindoc_1    | exit status 1 

```

**Comment by zhangxiangfeng** [comment]
今天准备从0.6开始升级呢. 本地测试了0.81 就卡到这里,

**Comment by bin20060407** [comment]
是calibre出错了
1. 建立一个test.txt，随便写点内容保存
2. 输入命令测试，就能看到报错信息了
``` bash
ebook-convert test.txt test.pdf
```

**Comment by zhangxiangfeng** [comment]
额  怎么处理?

**Comment by zhangxiangfeng** [comment]
@bin20060407  没有报错信息,都是正常输出

```
[root@9a7aed1804e1 mindoc]# ebook-convert 1.txt 1.pdf
1% Converting input to HTML...
InputFormatPlugin: TXT Input running
on /mindoc/1.txt
Language not specified
Creator not specified
Building file list...
Normalizing filename cases
Rewriting HTML links
flow is too short, not running heuristics
Forcing index.html into XHTML namespace
34% Running transforms on e-book...
Merging user specified metadata...
Detecting structure...
Auto generated TOC with 0 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Creating PDF Output...
67% Running PDF Output plugin
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/ebooks/conversion/cli.py", line 391, in main
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1252, in run
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 146, in convert
  File "site-packages/calibre/gui2/__init__.py", line 7, in <module>
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[root@9a7aed1804e1 mindoc]# ebook-convert  --version 
ebook-convert (calibre 3.16.0)
Created by: Kovid Goyal <kovid@kovidgoyal.net>

```

**Comment by zhangxiangfeng** [comment]
@bin20060407 确实是ebook-convert (calibre 3.16.0) 的问题.现在都搞好了. 但是 @lifei6671 感觉导出来的效果还没有原来0.6版本的好.

**Comment by lifei6671** [comment]
不应该吧。Calibre是专业做电子书的应用。解决了之前的PDF截断的问题。只是可能样式没那么漂亮，这个后期会优化。
