### ISSUE TITLE
无法正常导出PDF等文件

### ISSUE THREAD

**Issue by liminghui2011** [lifei6671/mindoc#363]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
github 上的最新版 mindoc_linux_amd64.zip

2. 你当前使用的是什么操作系统?
centos6.9

3. 你是如何操作的？
正常下载项目并部署启动，正常安装wkhtmltox、calibre

4. 你期望得到什么结果?
希望能正常导出文档文件

5. 当前遇到的是什么结果?
无法导出文档文件，提示错误：
Creating PDF Output...
67% 正在运行 PDF Output 插件
Traceback (most recent call last):
  File "site.py", line 66, in main
  File "site-packages/calibre/ebooks/conversion/cli.py", line 380, in main
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1222, in run
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 122, in convert
  File "site-packages/calibre/gui2/__init__.py", line 8, in <module>
ImportError: libGL.so.1: 无法打开共享对象文件: 没有那个文件或目录

**Comment by lifei6671** [comment]
Calibre插件安装有问题，请确保安装正确。
