### ISSUE TITLE
配置不成功，进入主界面失败

### ISSUE THREAD

**Issue by autoome** [lifei6671/mindoc#547]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.0，最新版本
2. 你当前使用的是什么操作系统?
windows10
3. 你是如何操作的？
在配置完成启动localhost：8181并登录后，报错，无法进入主界面。

4. 你期望得到什么结果?
配置成功进入系统

5. 当前遇到的是什么结果?
进入主界面失败，以下是报错信息：
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'member ON rel1.member_id = member.member_id
WHERE book.privately_owned = 0 or re' at line 9
2019/10/20 18:45:10.332 [D] [controller.go:283]  template Execute err: template: errors/error.tpl:10:17: executing "errors/error.tpl" at <eq 200 .ErrorCode>: error calling eq: invalid type for comparison
2019/10/20 18:45:10.333 [server.go:2977]  [HTTP] http: panic serving [::1]:56313: template: errors/error.tpl:10:17: executing "errors/error.tpl" at <eq 200 .ErrorCode>: error calling eq: invalid type for comparison
goroutine 161 [running]:
net/http.(*conn).serve.func1(0xc0000772c0)
        C:/go/src/net/http/server.go:1746 +0xd7
panic(0xc9ff20, 0xc0007f1f40)
        C:/go/src/runtime/panic.go:513 +0x1c7
github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego.executeError(0xc000566150, 0xc0007a09c0, 0x1f4)
        c:/gopath/src/github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego/error.go:467 +0x34a
github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego.exception(0xc0005788b3, 0x3, 0xc0007a09c0)
        c:/gopath/src/github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego/error.go:427 +0x1d0
github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego.recoverPanic(0xc0007a09c0)
        c:/gopath/src/github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego/config.go:171 +0x649
panic(0xc220c0, 0xc0004ca090)
        C:/go/src/runtime/panic.go:513 +0x1c7
github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego.(*Controller).CustomAbort(0xc00070c300, 0x1f4, 0xd24753, 0x3)
        c:/gopath/src/github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego/controller.go:326 +0x15b
github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego.(*Controller).Abort(0xc00070c300, 0xd24753, 0x3)
        c:/gopath/src/github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego/controller.go:318 +0x77
github.com/lifei6671/mindoc/controllers.(*HomeController).Index(0xc00070c300)
        c:/gopath/src/github.com/lifei6671/mindoc/controllers/HomeController.go:40 +0x211
reflect.Value.call(0xd1b380, 0xc00070c300, 0x8213, 0xd253d5, 0x4, 0x134ee40, 0x0, 0x0, 0xc189c0, 0x42, ...)
        C:/go/src/reflect/value.go:447 +0x450
reflect.Value.Call(0xd1b380, 0xc00070c300, 0x8213, 0x134ee40, 0x0, 0x0, 0x134ee40, 0x0, 0x0)
        C:/go/src/reflect/value.go:308 +0xab
github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego.(*ControllerRegister).ServeHTTP(0xc0000ac420, 0xe16d60, 0xc00013e1c0, 0xc0003add00)
        c:/gopath/src/github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego/router.go:852 +0x1ef9
net/http.serverHandler.ServeHTTP(0xc00010c820, 0xe16d60, 0xc00013e1c0, 0xc0003add00)
        C:/go/src/net/http/server.go:2741 +0xb2
net/http.(*conn).serve(0xc0000772c0, 0xe17260, 0xc00095c400)
        C:/go/src/net/http/server.go:1847 +0x64d
created by net/http.(*Server).Serve
        C:/go/src/net/http/server.go:2851 +0x2fc

**Comment by 107295472** [comment]
这是你数据库问题,mysql什么版本

**Comment by WenyuChou** [comment]
我也是遇到这个问题

**Comment by Jyishit** [comment]
我搞定了！！！这个鬼问题是因为有语法错误，我的解决方法是直接把mindoc的那个文件夹内的文件都删了然后重新解压再重新安装mindoc，我的系统是windows server 2019 ， sql用的是它官方那获取的server版本，现在已经成功做到内网访问了
