### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by jeffxjh** [lifei6671/mindoc#567]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.0

2. 你当前使用的是什么操作系统?
centos7

3. 你是如何操作的？
登录

4. 你期望得到什么结果?
想要登录，但是后台报错，错误代码如下，能否帮忙检查一下问题？

5. 当前遇到的是什么结果?
2019/12/30 11:01:34.879 [D] [controller.go:283]  template Execute err: template: errors/error.tpl:10:17: executing "errors/error.tpl" at <eq 200 .ErrorCode>: error calling eq: invalid type for comparison
2019/12/30 11:01:34.879 [server.go:3010]  [HTTP] http: panic serving 183.214.86.230:2557: template: errors/error.tpl:10:17: executing "errors/error.tpl" at <eq 200 .ErrorCode>: error calling eq: invalid type for comparison
goroutine 268 [running]:
net/http.(*conn).serve.func1(0xc0002c4000)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/net/http/server.go:1769 +0xc9
panic(0xc7ff60, 0xc0008118a0)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:522 +0x1b5
github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego.executeError(0xc0002c2990, 0xc0003eda70, 0x1f4)
	/home/travis/gopath/src/github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego/error.go:467 +0x361
github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego.exception(0xc0005b6ca3, 0x3, 0xc0003eda70)
	/home/travis/gopath/src/github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego/error.go:427 +0x247
github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego.recoverPanic(0xc0003eda70)
	/home/travis/gopath/src/github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego/config.go:171 +0x5d7
panic(0xbff3c0, 0xc000259b90)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:522 +0x1b5
github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego.(*Controller).CustomAbort(0xc0007b8600, 0x1f4, 0xd03fa6, 0x3)
	/home/travis/gopath/src/github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego/controller.go:326 +0x173
github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego.(*Controller).Abort(0xc0007b8600, 0xd03fa6, 0x3)
	/home/travis/gopath/src/github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego/controller.go:318 +0x70
github.com/lifei6671/mindoc/controllers.(*HomeController).Index(0xc0007b8600)
	/home/travis/gopath/src/github.com/lifei6671/mindoc/controllers/HomeController.go:40 +0x1f0
reflect.Value.call(0xcfb100, 0xc0007b8600, 0x8213, 0xd04bb6, 0x4, 0x160f350, 0x0, 0x0, 0xbf55c0, 0x42, ...)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/reflect/value.go:447 +0x461
reflect.Value.Call(0xcfb100, 0xc0007b8600, 0x8213, 0x160f350, 0x0, 0x0, 0x160f350, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/reflect/value.go:308 +0xa4
github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego.(*ControllerRegister).ServeHTTP(0xc00009c580, 0xe38620, 0xc0000dc000, 0xc0007b8100)
	/home/travis/gopath/src/github.com/lifei6671/mindoc/vendor/github.com/astaxie/beego/router.go:852 +0x1ee9
net/http.serverHandler.ServeHTTP(0xc000100410, 0xe38620, 0xc0000dc000, 0xc0007b8100)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/net/http/server.go:2774 +0xab
net/http.(*conn).serve(0xc0002c4000, 0xe3a6e0, 0xc0006ca000)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/net/http/server.go:1878 +0x84c
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/net/http/server.go:2884 +0x2f4

**Comment by drkingman** [comment]
same issue
