### ISSUE TITLE
为什么登录之后报错，只要输入admin 123456直接就崩溃了

### ISSUE THREAD

**Issue by 1229118978** [lifei6671/mindoc#631]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by 1229118978** [comment]
1最新版，windows adm64

**Comment by 1229118978** [comment]
2win10

**Comment by 1229118978** [comment]
[beego] 2020/10/10 - 15:51:10 |            ::1| 302 |    13.9607ms|   match| GET      /     r:/
[beego] 2020/10/10 - 15:51:10 |            ::1| 200 |    18.9479ms|   match| GET      /login   r:/login
[beego] 2020/10/10 - 15:51:10 |            ::1| 200 |     5.9836ms|   match| GET      /static/bootstrap/css/bootstrap.min.css
[beego] 2020/10/10 - 15:51:10 |            ::1| 200 |     3.9879ms|   match| GET      /static/font-awesome/css/font-awesome.min.css
[beego] 2020/10/10 - 15:51:10 |            ::1| 200 |     3.9881ms|   match| GET      /static/jquery/1.12.4/jquery.min.js
[beego] 2020/10/10 - 15:51:10 |            ::1| 200 |     3.9881ms|   match| GET      /static/css/main.css
[beego] 2020/10/10 - 15:51:10 |            ::1| 200 |      999.8µs|   match| GET      /static/layer/layer.js
[beego] 2020/10/10 - 15:51:10 |            ::1| 200 |     8.9755ms|   match| GET      /static/bootstrap/js/bootstrap.min.js
[beego] 2020/10/10 - 15:51:10 |            ::1| 200 |     2.9918ms|   match| GET      /static/font-awesome/fonts/fontawesome-webfont.woff2
[beego] 2020/10/10 - 15:51:10 |            ::1| 200 |     1.9946ms|   match| GET      /static/layer/skin/default/layer.css
[beego] 2020/10/10 - 15:51:10 |            ::1| 404 |     6.9822ms| nomatch| GET      /favicon.ico
2020/10/10 15:51:17.990 [E] [HomeController.go:39]  Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'member ON rel1.member_id = member.member_id
WHERE book.privately_owned = 0 or re' at line 9
2020/10/10 15:51:17.997 [D] [controller.go:283]  template Execute err: template: errors/error.tpl:10:17: executing "errors/error.tpl" at <eq 200 .ErrorCode>: error calling eq: invalid type for comparison
2020/10/10 15:51:17.997 [server.go:2977]  [HTTP] http: panic serving [::1]:39633: template: errors/error.tpl:10:17: executing "errors/error.tpl" at <eq 200 .ErrorCode>: error calling eq: invalid type for comparison
goroutine 227 [running]:
net/http.(*conn).serve.func1(0xc000916000)
        C:/go/src/net/http/server.go:1746 +0xd7
panic(0xc9ff20, 0xc0008fe800)

**Comment by 1229118978** [comment]
mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.17    |
+-----------+
1 row in set (0.00 sec)
